version: "3.8"

services:
  app:
    build: ./python-app/
    depends_on:
      - db
    command: sh -c "/wait && python3 add_data_in_db.py"
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=3
      - WAIT_SLEEP_INTERVAL=3
      - WAIT_HOST_CONNECT_TIMEOUT=3
  db:
    build: ./db/